package database.exam.solution;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table EXAM_SOLUTION.
*/
public class ExamSolutionDao extends AbstractDao<ExamSolution, Long> {

    public static final String TABLENAME = "EXAM_SOLUTION";

    /**
     * Properties of entity ExamSolution.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property ExamProblemId = new Property(1, Long.class, "examProblemId", false, "EXAM_PROBLEM_ID");
        public final static Property Result = new Property(2, Integer.class, "result", false, "RESULT");
        public final static Property SubmitTime = new Property(3, String.class, "submitTime", false, "SUBMIT_TIME");
        public final static Property RunningTime = new Property(4, Integer.class, "runningTime", false, "RUNNING_TIME");
        public final static Property RunningMemory = new Property(5, Integer.class, "runningMemory", false, "RUNNING_MEMORY");
    };


    public ExamSolutionDao(DaoConfig config) {
        super(config);
    }
    
    public ExamSolutionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'EXAM_SOLUTION' (" + //
                "'ID' INTEGER PRIMARY KEY ," + // 0: id
                "'EXAM_PROBLEM_ID' INTEGER," + // 1: examProblemId
                "'RESULT' INTEGER," + // 2: result
                "'SUBMIT_TIME' TEXT," + // 3: submitTime
                "'RUNNING_TIME' INTEGER," + // 4: runningTime
                "'RUNNING_MEMORY' INTEGER);"); // 5: runningMemory
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'EXAM_SOLUTION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ExamSolution entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long examProblemId = entity.getExamProblemId();
        if (examProblemId != null) {
            stmt.bindLong(2, examProblemId);
        }
 
        Integer result = entity.getResult();
        if (result != null) {
            stmt.bindLong(3, result);
        }
 
        String submitTime = entity.getSubmitTime();
        if (submitTime != null) {
            stmt.bindString(4, submitTime);
        }
 
        Integer runningTime = entity.getRunningTime();
        if (runningTime != null) {
            stmt.bindLong(5, runningTime);
        }
 
        Integer runningMemory = entity.getRunningMemory();
        if (runningMemory != null) {
            stmt.bindLong(6, runningMemory);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ExamSolution readEntity(Cursor cursor, int offset) {
        ExamSolution entity = new ExamSolution( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // examProblemId
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // result
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // submitTime
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // runningTime
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5) // runningMemory
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ExamSolution entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setExamProblemId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setResult(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setSubmitTime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRunningTime(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setRunningMemory(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ExamSolution entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ExamSolution entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
