package database.exam.solution;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SOLUTION.
 */
public class Solution {

    private Long id;
    private Long problemId;
    private Integer result;
    private Integer runningMemory;
    private Integer runningTime;
    private Integer echo;
    private String detail;
    private String source;
    private String submitTime;

    public Solution() {
    }

    public Solution(Long id) {
        this.id = id;
    }

    public Solution(Long id, Long problemId, Integer result, Integer runningMemory, Integer runningTime, Integer echo, String detail, String source, String submitTime) {
        this.id = id;
        this.problemId = problemId;
        this.result = result;
        this.runningMemory = runningMemory;
        this.runningTime = runningTime;
        this.echo = echo;
        this.detail = detail;
        this.source = source;
        this.submitTime = submitTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProblemId() {
        return problemId;
    }

    public void setProblemId(Long problemId) {
        this.problemId = problemId;
    }

    public Integer getResult() {
        return result;
    }

    public void setResult(Integer result) {
        this.result = result;
    }

    public Integer getRunningMemory() {
        return runningMemory;
    }

    public void setRunningMemory(Integer runningMemory) {
        this.runningMemory = runningMemory;
    }

    public Integer getRunningTime() {
        return runningTime;
    }

    public void setRunningTime(Integer runningTime) {
        this.runningTime = runningTime;
    }

    public Integer getEcho() {
        return echo;
    }

    public void setEcho(Integer echo) {
        this.echo = echo;
    }

    public String getDetail() {
        return detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getSubmitTime() {
        return submitTime;
    }

    public void setSubmitTime(String submitTime) {
        this.submitTime = submitTime;
    }


    public String getResultString() {
        String ret = "";
        switch (result) {
            case 0: ret = "通过"; break;
            case 2: ret = "超时"; break;
            case 3: ret = "超内存"; break;
            case 4: ret = "错误"; break;
            case 5: ret = "运行时错误"; break;
            case 7: ret = "编译错误"; break;
        }
        return ret;
    }
}
