package database.exam.paper;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import database.exam.paper.ExamPaper;

import database.exam.paper.ExamPaperDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig examPaperDaoConfig;

    private final ExamPaperDao examPaperDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        examPaperDaoConfig = daoConfigMap.get(ExamPaperDao.class).clone();
        examPaperDaoConfig.initIdentityScope(type);

        examPaperDao = new ExamPaperDao(examPaperDaoConfig, this);

        registerDao(ExamPaper.class, examPaperDao);
    }
    
    public void clear() {
        examPaperDaoConfig.getIdentityScope().clear();
    }

    public ExamPaperDao getExamPaperDao() {
        return examPaperDao;
    }

}
