package database.exam.paper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EXAM_PAPER.
 */
public class ExamPaper {

    private Long id;
    private String examPaper;

    public ExamPaper() {
    }

    public ExamPaper(Long id) {
        this.id = id;
    }

    public ExamPaper(Long id, String examPaper) {
        this.id = id;
        this.examPaper = examPaper;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getExamPaper() {
        return examPaper;
    }

    public void setExamPaper(String examPaper) {
        this.examPaper = examPaper;
    }

}
