package com.exam.solution;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.exam.solution.ExamSolution;

import com.exam.solution.ExamSolutionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig examSolutionDaoConfig;

    private final ExamSolutionDao examSolutionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        examSolutionDaoConfig = daoConfigMap.get(ExamSolutionDao.class).clone();
        examSolutionDaoConfig.initIdentityScope(type);

        examSolutionDao = new ExamSolutionDao(examSolutionDaoConfig, this);

        registerDao(ExamSolution.class, examSolutionDao);
    }
    
    public void clear() {
        examSolutionDaoConfig.getIdentityScope().clear();
    }

    public ExamSolutionDao getExamSolutionDao() {
        return examSolutionDao;
    }

}
