package database.exam.discuss;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import database.exam.discuss.Discuss;

import database.exam.discuss.DiscussDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig discussDaoConfig;

    private final DiscussDao discussDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        discussDaoConfig = daoConfigMap.get(DiscussDao.class).clone();
        discussDaoConfig.initIdentityScope(type);

        discussDao = new DiscussDao(discussDaoConfig, this);

        registerDao(Discuss.class, discussDao);
    }
    
    public void clear() {
        discussDaoConfig.getIdentityScope().clear();
    }

    public DiscussDao getDiscussDao() {
        return discussDao;
    }

}
