package database.exam.discuss;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DISCUSS.
 */
public class Discuss {

    private Long id;
    private Integer userID;
    private Long problemId;
    private String title;
    private String content;
    private String postTime;

    public Discuss() {
    }

    public Discuss(Long id) {
        this.id = id;
    }

    public Discuss(Long id, Integer userID, Long problemId, String title, String content, String postTime) {
        this.id = id;
        this.userID = userID;
        this.problemId = problemId;
        this.title = title;
        this.content = content;
        this.postTime = postTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUserID() {
        return userID;
    }

    public void setUserID(Integer userID) {
        this.userID = userID;
    }

    public Long getProblemId() {
        return problemId;
    }

    public void setProblemId(Long problemId) {
        this.problemId = problemId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getPostTime() {
        return postTime;
    }

    public void setPostTime(String postTime) {
        this.postTime = postTime;
    }

}
