package com.problem;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.problem.Problem;

import com.problem.ProblemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig problemDaoConfig;

    private final ProblemDao problemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        problemDaoConfig = daoConfigMap.get(ProblemDao.class).clone();
        problemDaoConfig.initIdentityScope(type);

        problemDao = new ProblemDao(problemDaoConfig, this);

        registerDao(Problem.class, problemDao);
    }
    
    public void clear() {
        problemDaoConfig.getIdentityScope().clear();
    }

    public ProblemDao getProblemDao() {
        return problemDao;
    }

}
