package com.exam;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.google.gson.annotations.SerializedName;

/**
 * Entity mapped to table EXAM.
 */
public class Exam {

    private Long id;
    private Long examId;
    private String title;
    @SerializedName("try")
    private Integer tries;
    private String description;
    private String startTime;
    private Integer last;
    private Double score;

    public Exam() {
    }

    public Exam(Long id) {
        this.id = id;
    }

    public Exam(Long id, Long examId, String title, Integer tries, String description, String startTime, Integer last, Double score) {
        this.id = id;
        this.examId = examId;
        this.title = title;
        this.tries = tries;
        this.description = description;
        this.startTime = startTime;
        this.last = last;
        this.score = score;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getExamId() {
        return examId;
    }

    public void setExamId(Long examId) {
        this.examId = examId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getTries() {
        return tries;
    }

    public void setTries(Integer tries) {
        this.tries = tries;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public Integer getLast() {
        return last;
    }

    public void setLast(Integer last) {
        this.last = last;
    }

    public Double getScore() {
        return score;
    }

    public void setScore(Double score) {
        this.score = score;
    }

}
