package database.exam.solution.list;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import database.exam.solution.list.SolutionList;

import database.exam.solution.list.SolutionListDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig solutionListDaoConfig;

    private final SolutionListDao solutionListDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        solutionListDaoConfig = daoConfigMap.get(SolutionListDao.class).clone();
        solutionListDaoConfig.initIdentityScope(type);

        solutionListDao = new SolutionListDao(solutionListDaoConfig, this);

        registerDao(SolutionList.class, solutionListDao);
    }
    
    public void clear() {
        solutionListDaoConfig.getIdentityScope().clear();
    }

    public SolutionListDao getSolutionListDao() {
        return solutionListDao;
    }

}
