package database.exam.solution.list;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import database.exam.solution.list.SolutionList;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SOLUTION_LIST.
*/
public class SolutionListDao extends AbstractDao<SolutionList, Long> {

    public static final String TABLENAME = "SOLUTION_LIST";

    /**
     * Properties of entity SolutionList.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Result = new Property(1, Integer.class, "result", false, "RESULT");
        public final static Property SubmitTime = new Property(2, String.class, "submitTime", false, "SUBMIT_TIME");
        public final static Property ProblemId = new Property(3, Long.class, "problemId", false, "PROBLEM_ID");
        public final static Property ExamProblemId = new Property(4, Long.class, "examProblemId", false, "EXAM_PROBLEM_ID");
        public final static Property RunningMemory = new Property(5, Integer.class, "runningMemory", false, "RUNNING_MEMORY");
        public final static Property Type = new Property(6, Integer.class, "type", false, "TYPE");
        public final static Property RunningTime = new Property(7, Integer.class, "runningTime", false, "RUNNING_TIME");
    };


    public SolutionListDao(DaoConfig config) {
        super(config);
    }
    
    public SolutionListDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SOLUTION_LIST' (" + //
                "'ID' INTEGER PRIMARY KEY ," + // 0: id
                "'RESULT' INTEGER," + // 1: result
                "'SUBMIT_TIME' TEXT," + // 2: submitTime
                "'PROBLEM_ID' INTEGER," + // 3: problemId
                "'EXAM_PROBLEM_ID' INTEGER," + // 4: examProblemId
                "'RUNNING_MEMORY' INTEGER," + // 5: runningMemory
                "'TYPE' INTEGER," + // 6: type
                "'RUNNING_TIME' INTEGER);"); // 7: runningTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SOLUTION_LIST'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SolutionList entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer result = entity.getResult();
        if (result != null) {
            stmt.bindLong(2, result);
        }
 
        String submitTime = entity.getSubmitTime();
        if (submitTime != null) {
            stmt.bindString(3, submitTime);
        }
 
        Long problemId = entity.getProblemId();
        if (problemId != null) {
            stmt.bindLong(4, problemId);
        }
 
        Long examProblemId = entity.getExamProblemId();
        if (examProblemId != null) {
            stmt.bindLong(5, examProblemId);
        }
 
        Integer runningMemory = entity.getRunningMemory();
        if (runningMemory != null) {
            stmt.bindLong(6, runningMemory);
        }
 
        Integer type = entity.getType();
        if (type != null) {
            stmt.bindLong(7, type);
        }
 
        Integer runningTime = entity.getRunningTime();
        if (runningTime != null) {
            stmt.bindLong(8, runningTime);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SolutionList readEntity(Cursor cursor, int offset) {
        SolutionList entity = new SolutionList( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // result
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // submitTime
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // problemId
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // examProblemId
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // runningMemory
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // type
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7) // runningTime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SolutionList entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setResult(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setSubmitTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setProblemId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setExamProblemId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setRunningMemory(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setType(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setRunningTime(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SolutionList entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SolutionList entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
